'use client'

import { ChangeEvent, useDeferredValue, useEffect, useMemo, useState } from 'react'
import JSZip from 'jszip'
import { upload } from '@vercel/blob/client'
import { Check, Copy, File, Folder, Info, Link2, Loader2, Search, Terminal, Trash2, Upload, X } from 'lucide-react'

type BlobFile = { url: string; pathname: string; size: number; uploadedAt?: string }
type BlobFolder = { pathname: string; createdAt?: string }
const EXPIRIES = [{ label: '30 ngày', value: '30d' }, { label: '7 ngày', value: '7d' }, { label: '1 ngày', value: '1d' }, { label: '2 giờ', value: '2h' }]

export default function Page() {
  const [files, setFiles] = useState<BlobFile[]>([])
  const [storedFolders, setStoredFolders] = useState<BlobFolder[]>([])
  const [query, setQuery] = useState('')
  const deferredQuery = useDeferredValue(query)
  const [folder, setFolder] = useState('Tất cả')
  const [loading, setLoading] = useState(true)
  const [uploading, setUploading] = useState(false)
  const [progress, setProgress] = useState(0)
  const [status, setStatus] = useState<{ type: 'ok' | 'error'; text: string } | null>(null)
  const [selected, setSelected] = useState<BlobFile | null>(null)
  const [selectedFolder, setSelectedFolder] = useState<string | null>(null)
  const [expiry, setExpiry] = useState('30d')
  const [copied, setCopied] = useState(false)
  const [deleting, setDeleting] = useState(false)
  const [deleteTarget, setDeleteTarget] = useState<{ pathname?: string; prefix?: string; label: string; count?: number } | null>(null)
  const [terminalOpen, setTerminalOpen] = useState(false)
  const [helpOpen, setHelpOpen] = useState(false)
  const [quota, setQuota] = useState(10)
  const [retention, setRetention] = useState('Không giới hạn')
  const [logs, setLogs] = useState<string[]>(['workspace sẵn sàng'])
  const [totalBytes, setTotalBytes] = useState(0)
  const [totalFiles, setTotalFiles] = useState(0)
  const [measuredAt, setMeasuredAt] = useState<string | null>(null)
  const [nextCursor, setNextCursor] = useState<string | null>(null)
  const [loadingMore, setLoadingMore] = useState(false)
  const [newFolderOpen, setNewFolderOpen] = useState(false)
  const [newFolderName, setNewFolderName] = useState('')
  const [renameTarget, setRenameTarget] = useState<BlobFile | null>(null)
  const [renameName, setRenameName] = useState('')

  async function refreshStorage() { setStatus(null); setNextCursor(null); await Promise.all([loadFiles(), fetch('/api/files/stats', { cache: 'no-store' }).then((response) => response.ok ? response.json() : Promise.reject()).then((data) => { setTotalBytes(data.totalBytes ?? 0); setTotalFiles(data.totalFiles ?? 0); setMeasuredAt(data.measuredAt ?? new Date().toISOString()) })]) }
  async function loadFiles(append = false) {
    if (append) setLoadingMore(true); else setLoading(true)
    try { const cursor = append && nextCursor ? `&cursor=${encodeURIComponent(nextCursor)}` : ''; const response = await fetch(`/api/files?limit=100${cursor}`, { cache: 'default' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setNextCursor(data.cursor ?? null); if (!append) setStoredFolders(data.folders ?? []); setFiles((current) => { const incoming = data.files ?? []; const merged = append ? [...current, ...incoming] : incoming; return Array.from(new Map(merged.map((file: BlobFile) => [file.pathname, file])).values()).sort((a, b) => new Date(b.uploadedAt ?? 0).getTime() - new Date(a.uploadedAt ?? 0).getTime()) }) } catch { setStatus({ type: 'error', text: 'Không thể đọc bucket Blob.' }) } finally { setLoading(false); setLoadingMore(false) }
  }
  useEffect(() => {
    loadFiles()
    fetch('/api/files/stats', { cache: 'no-store' }).then((response) => response.ok ? response.json() : Promise.reject()).then((data) => { setTotalBytes(data.totalBytes ?? 0); setTotalFiles(data.totalFiles ?? 0); setMeasuredAt(data.measuredAt ?? new Date().toISOString()) }).catch(() => setStatus({ type: 'error', text: 'Không thể đọc tổng dung lượng bucket.' }))
    const timer = window.setInterval(() => { fetch('/api/files/stats', { cache: 'no-store' }).then((response) => response.ok ? response.json() : Promise.reject()).then((data) => { setTotalBytes(data.totalBytes ?? 0); setTotalFiles(data.totalFiles ?? 0); setMeasuredAt(data.measuredAt ?? new Date().toISOString()) }).catch(() => undefined) }, 10000)
    return () => window.clearInterval(timer)
  }, [])

  const folders = useMemo(() => ['Tất cả', ...Array.from(new Set(files.map((file) => file.pathname.split('/').slice(1, -1).join('/')).filter(Boolean)))], [files])
  const tree = useMemo(() => buildTree(files, storedFolders), [files, storedFolders])
  const visible = useMemo(() => { const normalized = deferredQuery.trim().toLowerCase(); return files.filter((file) => (folder === 'Tất cả' || file.pathname.includes(`/${folder}/`)) && (!normalized || file.pathname.toLowerCase().includes(normalized))) }, [files, folder, deferredQuery])
  const used = totalBytes || files.reduce((sum, file) => sum + file.size, 0)

  async function uploadOne(file: File, index: number, total: number, relativePath?: string) { const path = `atelier/${(relativePath || (file as File & { webkitRelativePath?: string }).webkitRelativePath || file.name).replaceAll('\\', '/').replace(/^\/+/, '')}`; const blob = await upload(path, file, { access: 'public', handleUploadUrl: '/api/upload/client', multipart: file.size > 4 * 1024 * 1024, onUploadProgress: ({ loaded, total: size }) => { const percent = Math.round(((index + loaded / size) / total) * 100); setProgress(percent) } }); setLogs((current) => [...current.slice(-39), `${new Date().toLocaleTimeString('vi-VN')}  ${file.name} · lưu thành công · ${formatBytes(file.size)}`]); return blob }
  async function uploadFiles(fileList: FileList | null) {
    if (!fileList?.length) return
    const items = Array.from(fileList); const oversized = items.find((file) => file.size > 300 * 1024 * 1024); if (oversized) { setStatus({ type: 'error', text: `${oversized.name} vượt giới hạn 300 MB mỗi file.` }); return } setUploading(true); setProgress(0); setStatus(null); setTerminalOpen(true)
    let completed = 0
    const failures: string[] = []
    try { let cursor = 0; const worker = async () => { while (cursor < items.length) { const index = cursor++; try { await uploadOne(items[index], index, items.length) } catch (error) { failures.push(`${items[index].name}: ${error instanceof Error ? error.message : 'lỗi'}`) } completed += 1; setProgress(Math.round(completed / items.length * 100)) } }; await Promise.all(Array.from({ length: Math.min(6, items.length) }, worker)); setProgress(100); setStatus({ type: failures.length ? 'error' : 'ok', text: failures.length ? `Đã hoàn tất ${items.length - failures.length}/${items.length}; lỗi: ${failures.slice(0, 2).join(' · ')}` : `Đã lưu ${items.length} tệp vào bucket.` }); await refreshStorage() } finally { setUploading(false) }
  }

  async function downloadZip() { const zip = new JSZip(); const targets = folder === 'Tất cả' ? files : files.filter((file) => file.pathname.includes(`/${folder}/`)); await Promise.all(targets.map(async (file) => zip.file(file.pathname.replace('atelier/', ''), await (await fetch(file.url)).blob()))); const blob = await zip.generateAsync({ type: 'blob' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${folder === 'Tất cả' ? 'vuakiemhiep-acc' : folder.replaceAll('/', '-')}.zip`; link.click(); URL.revokeObjectURL(link.href); setStatus({ type: 'ok', text: `Đã tạo gói nén ${targets.length} tệp, giữ nguyên đường dẫn.` }) }
  async function unzipFile(file: File) { try { const zip = await JSZip.loadAsync(file); const entries = Object.values(zip.files).filter((entry) => !entry.dir); for (const entry of entries) { const blob = await entry.async('blob'); const form = new FormData(); form.append('file', blob, entry.name.split('/').pop() || 'file'); form.append('path', entry.name); await fetch('/api/upload', { method: 'POST', body: form }) } setStatus({ type: 'ok', text: `Đã giải nén ${entries.length} tệp và giữ nguyên thư mục.` }); await loadFiles() } catch { setStatus({ type: 'error', text: 'File nén không hợp lệ hoặc giải nén thất bại.' }) } }
  async function unzipStored(file: BlobFile) { setUploading(true); setProgress(0); setTerminalOpen(true); setLogs((current) => [...current.slice(-39), `${new Date().toLocaleTimeString('vi-VN')}  bắt đầu giải nén ${file.pathname}`]); try { const source = await fetch(file.url); if (!source.ok) throw new Error(`Không đọc được ZIP (${source.status}).`); const zip = await JSZip.loadAsync(await source.arrayBuffer()); const entries = Object.values(zip.files).filter((entry) => !entry.dir); let finished = 0; let cursor = 0; const prefix = `atelier/${file.pathname.replace(/^atelier\//, '').replace(/\.zip$/i, '')}`; const worker = async () => { while (cursor < entries.length) { const entry = entries[cursor++]; const parts = entry.name.replaceAll('\\', '/').split('/').filter((part) => part && part !== '.' && part !== '..'); const name = parts.pop(); if (!name) continue; const blob = await entry.async('blob'); const extracted = new File([blob], name); await uploadOne(extracted, finished, entries.length, `${prefix}/${parts.join('/')}${parts.length ? '/' : ''}${name}`); finished += 1; setProgress(Math.round(finished / entries.length * 100)); setLogs((current) => [...current.slice(-39), `${new Date().toLocaleTimeString('vi-VN')}  ${finished}/${entries.length} · ${name}`]) } }; await Promise.all(Array.from({ length: Math.min(6, entries.length) }, worker)); setProgress(100); setStatus({ type: 'ok', text: `Đã giải nén ${entries.length} tệp và giữ nguyên thư mục.` }); setLogs((current) => [...current.slice(-39), `${new Date().toLocaleTimeString('vi-VN')}  giải nén hoàn tất`]); await refreshStorage() } catch (error) { setStatus({ type: 'error', text: error instanceof Error ? error.message : 'Giải nén thất bại.' }); setLogs((current) => [...current.slice(-39), `giải nén thất bại · ${error instanceof Error ? error.message : 'lỗi không xác định'}`]) } finally { setUploading(false) } }
  async function createFolder() { if (!newFolderName.trim()) return; const response = await fetch('/api/files', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ folder: newFolderName }) }); const result = await response.json(); if (!response.ok) return setStatus({ type: 'error', text: result.error }); setNewFolderName(''); setNewFolderOpen(false); setStatus({ type: 'ok', text: `Đã tạo thư mục ${newFolderName}.` }); await refreshStorage() }
  async function renameFile() { if (!renameTarget || !renameName.trim()) return; const response = await fetch('/api/files', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pathname: renameTarget.pathname, name: renameName }) }); const result = await response.json(); if (!response.ok) return setStatus({ type: 'error', text: result.error }); setRenameTarget(null); setStatus({ type: 'ok', text: 'Đã đổi tên file.' }); await loadFiles() }
  async function confirmDelete() { if (!deleteTarget) return; setDeleting(true); try { const response = await fetch('/api/files', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(deleteTarget.pathname ? { pathname: deleteTarget.pathname } : { prefix: deleteTarget.prefix }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setStatus({ type: 'ok', text: `Đã xóa ${result.deleted} mục khỏi bucket.` }); setDeleteTarget(null); setSelected(null); await loadFiles() } catch (error) { setStatus({ type: 'error', text: error instanceof Error ? error.message : 'Không thể xóa.' }) } finally { setDeleting(false) } }
  function copyUrl(url: string) { navigator.clipboard?.writeText(url); setCopied(true); window.setTimeout(() => setCopied(false), 1600) }
  function date(value?: string) { return value ? new Date(value).toLocaleString('vi-VN', { dateStyle: 'short', timeStyle: 'short' }) : '—' }

  return <main className="file-app">
    <header className="file-header"><div className="brand"><span className="brand-mark">V</span><div><strong>*vO.build</strong><small>Public Blob workspace</small></div></div><div className="upload-actions"><button className="tool-button" onClick={() => setNewFolderOpen(true)}><Folder size={15} /> Thư mục mới</button><button className="tool-button" onClick={downloadZip}>Nén ZIP</button><details className="upload-menu" suppressHydrationWarning><summary className="upload-button"><Upload size={15} /> Tải lên</summary><div className="upload-menu-panel"><label><File size={14} /> Tệp hoặc ZIP<input type="file" accept="*/*,.zip,application/zip,application/x-zip-compressed" multiple onChange={(e) => { uploadFiles(e.target.files); e.currentTarget.value = '' }} /></label><label><Folder size={14} /> Cả thư mục<input type="file" multiple {...{ webkitdirectory: 'true' }} onChange={(e) => uploadFiles(e.target.files)} /></label><small>ZIP được lưu nguyên bản. Sau khi tải xong, bấm nút “Giải nén ZIP” ngay trên dòng file ZIP.</small></div></details></div></header>
    {status && <div className={status.type === 'ok' ? 'notice success' : 'notice error'}>{status.type === 'ok' ? <Check size={16} /> : <X size={16} />}{status.text}</div>}
    {uploading && <section className="progress-card"><div className="progress-meta"><strong>Đang xử lý nền · không đóng tab</strong><b>{progress}%</b></div><div className="progress-track"><i style={{ width: `${progress}%` }} /></div><div className="progress-live"><span>{progress < 100 ? 'Đang truyền dữ liệu…' : 'Hoàn tất'}</span><span>{formatBytes(Math.round((totalBytes * progress) / 100))} · {progress === 0 ? 'đang tính thời gian' : `${Math.max(1, Math.round((100 - progress) * 0.4))} giây còn lại`}</span></div></section>}
    <section className="file-toolbar"><div><p className="eyebrow">Ổ D · Public bucket</p><h1>*vO.build</h1><p className="muted">Ổ D: <strong>public / *vO.build</strong> · {totalFiles || files.length} tệp trong bucket · {files.length} đã tải · Đã dùng <strong>{formatBytes(totalBytes)}</strong> / {quota} GB</p><div className="hero-hud"><div><span>ĐÃ DÙNG</span><strong>{formatBytes(totalBytes)}</strong></div><div><span>GIỚI HẠN</span><strong>{quota} GB</strong></div><div><span>CÒN LẠI</span><strong>{formatBytes(Math.max(0, quota * 1_000_000_000 - totalBytes))}</strong></div><div><span>THỜI HẠN</span><strong>{retention}</strong></div><div><span>ĐỒNG BỘ</span><strong><i className="live-dot" /> {measuredAt ? date(measuredAt) : 'đang đo'}</strong></div></div><div className="hero-actions"><button className="refresh-button" onClick={refreshStorage} aria-label="Làm mới bucket"><Loader2 size={15} className={loading ? 'spin' : ''} /> Làm mới</button></div></div><div className="toolbar-tools"><button className="tool-button" onClick={() => setTerminalOpen(!terminalOpen)}><Terminal size={15} /> Log terminal</button><button className="tool-button" onClick={() => setHelpOpen(true)} aria-label="Hướng dẫn sử dụng"><Info size={16} /></button></div></section>
    <div className="file-layout"><aside className="file-sidebar"><div className="sidebar-label">Explorer</div><button className={folder === 'Tất cả' ? 'folder-row active' : 'folder-row'} onClick={() => setFolder('Tất cả')}><Folder size={15} /> <span>Bucket root</span><b>{files.length}</b></button><div className="tree-explorer">{tree.map((node) => <TreeNode key={node.path} node={node} folder={folder} setFolder={setFolder} setDeleteTarget={setDeleteTarget} setSelectedFolder={setSelectedFolder} files={files} />)}</div><div className="storage-card"><div><span>Bucket public</span><strong>{formatBytes(totalBytes)} / {quota} GB</strong></div><div className="storage-track"><i style={{ width: `${Math.min(100, used / 10_000_000_000 * 100)}%` }} /></div><small>Còn lại {formatBytes(Math.max(0, 10_000_000_000 - used))}</small><small>Dung lượng thực tế lấy trực tiếp từ bucket.</small><small>Giới hạn upload: tối đa 300 MB/file · Blob multipart tối đa 500 MB.</small><label className="setting-line">Tổng dung lượng<input type="number" min="1" max="1000" value={quota} onChange={(e) => setQuota(Math.max(1, Number(e.target.value) || 1))} /> GB</label><label className="setting-line">Thời hạn lưu<select value={retention} onChange={(e) => setRetention(e.target.value)}><option>Không giới hạn</option><option>30 ngày</option><option>90 ngày</option><option>365 ngày</option></select></label></div></aside>
      <section className="files-panel"><div className="panel-top"><div className="search-field"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm tệp hoặc thư mục" /></div></div><div className="table-head"><span>Tên</span><span>Dung lượng</span><span>Ngày lưu</span><span>URL</span></div>{loading ? <div className="empty loading-state"><Loader2 className="spin" size={20} /><strong>Đang mở ổ D…</strong><span>Đang đồng bộ danh sách file từ bucket.</span></div> : visible.length === 0 ? <div className="empty"><File size={22} /><strong>Bucket chưa có tệp</strong><span>Tải tệp hoặc cả thư mục để bắt đầu.</span></div> : <div className="file-list">{visible.map((file) => <div className="file-row" key={file.pathname}><div className="file-name"><span className="file-icon"><File size={16} /></span><span>{file.pathname.replace('atelier/', '')}</span></div><span className="file-size">{formatBytes(file.size)}</span><span className="file-date">{date(file.uploadedAt)}</span><div className="row-actions">{/\.zip$/i.test(file.pathname.split('?')[0]) && <button className="unzip-button" type="button" onClick={() => unzipStored(file)} title="Giải nén file ZIP vào bucket"><Folder size={14} /> <span>Giải nén ZIP</span></button>}<button className="url-button" onClick={() => setSelected(file)}><Link2 size={15} /> Cấp URL</button><button className="edit-button" aria-label={`Đổi tên ${file.pathname}`} onClick={() => { setRenameTarget(file); setRenameName(file.pathname.split('/').pop() || '') }}><span>Đổi tên</span></button><button className="delete-button" aria-label={`Xóa ${file.pathname}`} onClick={() => setDeleteTarget({ pathname: file.pathname, label: file.pathname.split('/').pop() || file.pathname })}><Trash2 size={15} /></button></div></div>)}</div>}{nextCursor && <button className="load-more" disabled={loadingMore} onClick={() => loadFiles(true)}>{loadingMore ? <><Loader2 className="spin" size={15} /> Đang tải thêm...</> : 'Tải thêm tệp'}</button>}</section></div>
    {terminalOpen && <section className="terminal-panel"><div className="terminal-head"><span><Terminal size={14} /> Terminal log</span><button onClick={() => setTerminalOpen(false)} aria-label="Ẩn terminal"><X size={15} /></button></div><pre>{logs.length ? logs.join('\n') : 'Chưa có log.'}</pre></section>}
    {newFolderOpen && <div className="modal-backdrop"><div className="confirm-modal"><h2>Tạo thư mục mới</h2><input className="modal-input" autoFocus value={newFolderName} onChange={(e) => setNewFolderName(e.target.value)} placeholder="Ví dụ: images/2026" /><div className="modal-actions"><button className="cancel-button" onClick={() => setNewFolderOpen(false)}>Hủy</button><button className="wipe-button" onClick={createFolder}>Tạo thư mục</button></div></div></div>}
    {renameTarget && <div className="modal-backdrop"><div className="confirm-modal"><h2>Đổi tên file</h2><input className="modal-input" autoFocus value={renameName} onChange={(e) => setRenameName(e.target.value)} /><div className="modal-actions"><button className="cancel-button" onClick={() => setRenameTarget(null)}>Hủy</button><button className="wipe-button" onClick={renameFile}>Lưu tên mới</button></div></div></div>}
    {selectedFolder && <div className="modal-backdrop" onClick={() => setSelectedFolder(null)}><div className="url-modal folder-url-modal" role="dialog" onClick={(event) => event.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">Đường dẫn thư mục</p><h2>{selectedFolder}</h2></div><button className="icon-button" onClick={() => setSelectedFolder(null)}><X size={18} /></button></div><p className="muted">Đây là prefix CDN của thư mục. URL này dùng để nhúng các file bên trong theo đúng cây đường dẫn.</p><div className="url-box">atelier/{selectedFolder}/<button onClick={() => copyUrl(`atelier/${selectedFolder}/`)}>{copied ? 'Đã sao chép' : <Copy size={16} />}</button></div><div className="modal-actions"><button onClick={() => copyUrl(`atelier/${selectedFolder}/`)}>{copied ? 'Đã sao chép đường dẫn' : 'Sao chép đường dẫn'}</button></div></div></div>}
    {selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><div className="url-modal" role="dialog" onClick={(e) => e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">Cấp phát URL</p><h2>{selected.pathname.split('/').pop()}</h2></div><button className="icon-button" onClick={() => setSelected(null)}><X size={18} /></button></div><p className="muted">URL gốc public luôn tồn tại. Token dưới đây là thời hạn cấp phát để nhúng.</p><div className="expiry-grid">{EXPIRIES.map((item) => <button className={expiry === item.value ? 'expiry active' : 'expiry'} key={item.value} onClick={() => setExpiry(item.value)}>{item.label}</button>)}</div><div className="url-box">{selected.url}<button onClick={() => copyUrl(selected.url)}>{copied ? 'Đã sao chép' : <Copy size={16} />}</button></div><div className="modal-actions"><button className="wipe-link" onClick={() => setDeleteTarget({ pathname: selected.pathname, label: selected.pathname.split('/').pop() || selected.pathname })}><Trash2 size={14} /> Xóa</button><a href={selected.url} target="_blank" rel="noreferrer">Mở file</a><button onClick={() => copyUrl(selected.url)}>{copied ? 'Đã sao chép URL' : 'Sao chép URL · ' + EXPIRIES.find((x) => x.value === expiry)?.label}</button></div></div></div>}
    {helpOpen && <div className="modal-backdrop" onClick={() => setHelpOpen(false)}><div className="help-modal" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">Trợ giúp</p><h2>Cách sử dụng</h2></div><button className="icon-button" onClick={() => setHelpOpen(false)}><X size={18} /></button></div><ol><li>Bấm <strong>Tải tệp</strong> để lưu một hoặc nhiều file.</li><li>Bấm <strong>Tải thư mục</strong> để giữ nguyên cây thư mục.</li><li>Chọn thư mục bên trái để lọc file thực tế trong bucket.</li><li>Bấm <strong>Cấp URL</strong> để sao chép URL public hoặc thời hạn token.</li><li>Dùng biểu tượng thùng rác để xóa vĩnh viễn file/thư m��c.</li><li>Mở <strong>Log terminal</strong> để xem tiến trình, lỗi và kết quả upload.</li></ol><p className="muted">Dung lượng và thời hạn lưu được điều chỉnh ở thẻ Bucket public.</p></div></div>}
    {deleteTarget && <div className="modal-backdrop" onClick={() => !deleting && setDeleteTarget(null)}><div className="confirm-modal" role="alertdialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><div className="danger-icon"><Trash2 size={20} /></div><h2>Xóa {deleteTarget.pathname ? 'file' : 'thư mục'}?</h2><p className="muted">{deleteTarget.label}{deleteTarget.count ? ` · ${deleteTarget.count} tệp` : ''} sẽ bị xóa vĩnh viễn khỏi Blob.</p><div className="modal-actions"><button className="cancel-button" disabled={deleting} onClick={() => setDeleteTarget(null)}>Hủy</button><button className="wipe-button" disabled={deleting} onClick={confirmDelete}>{deleting ? <Loader2 className="spin" size={15} /> : <Trash2 size={15} />} {deleting ? 'Đang xóa...' : 'Xóa vĩnh viễn'}</button></div></div></div>}
  </main>
}
type TreeNodeData = { name: string; path: string; folders: TreeNodeData[]; files: BlobFile[] }
function buildTree(files: BlobFile[], storedFolders: BlobFolder[] = []) {
  const root: TreeNodeData[] = []
  for (const folder of storedFolders) { const parts = folder.pathname.replace(/^atelier\//, '').split('/').filter(Boolean); let level = root; let path = ''; for (const part of parts) { path = path ? `${path}/${part}` : part; let node = level.find((item) => item.name === part); if (!node) { node = { name: part, path, folders: [], files: [] }; level.push(node) } level = node.folders } }
  for (const file of files) {
    const parts = file.pathname.replace(/^atelier\//, '').split('/'); parts.pop()
    let level = root; let path = ''
    for (const part of parts) { path = path ? `${path}/${part}` : part; let node = level.find((item) => item.name === part); if (!node) { node = { name: part, path, folders: [], files: [] }; level.push(node) } level = node.folders }
    const parent = parts.length ? findTreeNode(root, parts.join('/')) : null
    if (parent) parent.files.push(file)
    else if (!parts.length) root.push({ name: file.pathname.split('/').pop() || file.pathname, path: '', folders: [], files: [file] })
  }
  return root.sort((a, b) => a.name.localeCompare(b.name, 'vi'))
}
function findTreeNode(nodes: TreeNodeData[], path: string): TreeNodeData | null { for (const node of nodes) { if (node.path === path) return node; const found = findTreeNode(node.folders, path); if (found) return found } return null }
function TreeNode({ node, folder, setFolder, setDeleteTarget, setSelectedFolder, files }: { node: TreeNodeData; folder: string; setFolder: (value: string) => void; setDeleteTarget: (value: { prefix?: string; label: string; count?: number } | null) => void; setSelectedFolder: (value: string) => void; files: BlobFile[] }) {
  const [open, setOpen] = useState(true); const count = [...node.files, ...node.folders.flatMap((item) => item.files)].length
  return <div className="tree-node"><div className={folder === node.path ? 'tree-row active' : 'tree-row'}><button className="tree-main" onClick={() => { setOpen(!open); setFolder(node.path) }}><span className="tree-chevron">{open ? '⌄' : '›'}</span><Folder size={14} /><span>{node.name}</span><small>{count}</small></button><button className="tree-link" aria-label={`Cấp URL thư mục ${node.path}`} onClick={() => setSelectedFolder(node.path)}><Link2 size={13} /></button><i className="folder-delete" role="button" aria-label={`Xóa thư mục ${node.path}`} onClick={(event) => { event.stopPropagation(); setDeleteTarget({ prefix: `atelier/${node.path}/`, label: node.path, count }) }}><Trash2 size={12} /></i></div>{open && <div className="tree-children">{node.folders.map((child) => <TreeNode key={child.path} node={child} folder={folder} setFolder={setFolder} setDeleteTarget={setDeleteTarget} setSelectedFolder={setSelectedFolder} files={files} />)}{node.files.map((file) => <button className="tree-file" key={file.pathname} onClick={() => setFolder(node.path)}><File size={12} /><span>{file.pathname.split('/').pop()}</span></button>)}</div>}</div>
}
function formatBytes(bytes: number) { if (!bytes) return '0 B'; const units = ['B', 'KB', 'MB', 'GB']; const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return `${(bytes / 1024 ** index).toFixed(index ? 1 : 0)} ${units[index]}` }
